document.addEventListener("DOMContentLoaded",()=>{
 const session=vbGetSession();if(!session||session.role!=="admin"){location.href="login.html";return}
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
 const toast=(m,t="success")=>{const e=$("#toast");e.textContent=m;e.className=`toast show ${t}`;clearTimeout(window._toast);window._toast=setTimeout(()=>e.className="toast",3200)};
 const phoneCodes=["+233","+1","+44","+234","+254","+27","+20","+971","+966","+91","+86","+81","+82","+33","+49","+39","+34","+31","+41","+61","+64","+55","+52","+7","+90","+65"];
 const normalizePhone=(code,number)=>{let raw=String(number||"").trim(); if(!raw)return ""; let n=raw.replace(/[\s().-]/g,""); if(!/^\+?\d{6,15}$/.test(n.replace(/^00/,"+")))throw new Error("Enter a valid international phone number."); if(n.startsWith("+"))return n; if(n.startsWith("00"))return "+"+n.slice(2); if(n.startsWith("0"))n=n.slice(1); return code+n};
 const splitPhone=(phone)=>{const p=String(phone||"").trim().replace(/[^+\d]/g,""); const code=phoneCodes.find(x=>p.startsWith(x))||"+233"; return {code,local:p.startsWith(code)?p.slice(code.length):p.replace(/^\+/,"")};};
 const statusClass=s=>s==="Active"?"badge-success":s==="Frozen"||s==="Closed"?"badge-danger":"badge-pending";
 const clientFor=(tx,s)=>s.clients.find(c=>c.id===tx.clientId), typeLabel=t=>t==="deposit"?"Deposit":t==="withdrawal"?"Withdrawal":t==="transfer_in"?"Transfer received":"Transfer sent";
 function switchSection(name){$$('.dashboard-section').forEach(s=>s.classList.remove('active'));$("#"+name+"Section").classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===name));$("#pageTitle").textContent={overview:"System Overview",clients:"Client Accounts",transactions:"System Transactions",audit:"Audit Trail",settings:"System Settings"}[name];$("#sidebar").classList.remove('open');$("#mobileOverlay").classList.remove('open')}
 function modal(id,on=true){$("#"+id).classList.toggle('open',on)}
 function totalsByCurrency(items){const out={USD:0,GBP:0,EUR:0};items.forEach(x=>{const code=x.currency||vbFindClient(x.clientId)?.currency||"USD";out[code]=(out[code]||0)+Number(x.amount||0)});return Object.entries(out).filter(([,v])=>v!==0).map(([k,v])=>vbFormatMoney(v,k)).join(" • ")||"$0.00"}
 function renderStats(){const s=vbGetState(),de=s.transactions.filter(t=>t.type==="deposit"),wd=s.transactions.filter(t=>t.type==="withdrawal"),sent=s.transactions.filter(t=>t.type==="transfer_out"),assets=s.clients;$("#adminStats").innerHTML=[["Active clients",s.clients.filter(c=>c.status==="Active").length,"Registered accounts","blue"],["Total balances",totalsByCurrency(assets.map(c=>({amount:c.balance,currency:c.currency}))),"By account currency","gold"],["Deposits",totalsByCurrency(de),"All-time deposits","green"],["Withdrawals",totalsByCurrency(wd),"All-time withdrawals","red"],["Transfers",totalsByCurrency(sent),"Sender-side volume","blue"],["Transactions",s.transactions.length,"Ledger entries","gold"]].map(x=>`<article class="stat-card glass"><div class="stat-top"><span>${x[0]}</span><span class="stat-icon ${x[3]}">◈</span></div><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('')}
 function renderChart(){const s=vbGetState(),days=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10),count=s.transactions.filter(t=>t.timestamp.slice(0,10)===key).length;days.push({label:d.toLocaleDateString('en-US',{weekday:'short'}),count})}const max=Math.max(...days.map(x=>x.count),1);$("#volumeChart").innerHTML=days.map(d=>`<div class="bar-col"><div class="bar-value">${d.count||''}</div><div class="bar-track"><i style="height:${Math.max(5,d.count/max*100)}%"></i></div><span>${d.label}</span></div>`).join('')}
 function renderStatus(){const s=vbGetState(),total=Math.max(s.clients.length,1),statuses=[['Active','green'],['Frozen','red'],['Suspended','gold'],['Closed','blue']];$("#statusBreakdown").innerHTML=statuses.map(([st,c])=>{const n=s.clients.filter(x=>x.status===st).length;return `<div class="status-line"><div><span>${st}</span><strong>${n}</strong></div><div class="status-bar"><i class="${c}" style="width:${n/total*100}%"></i></div></div>`}).join('')}
 function renderRecent(){const s=vbGetState();$("#recentTransactions").innerHTML=s.transactions.slice(0,7).map(t=>{const c=clientFor(t,s),positive=t.type==="deposit"||t.type==="transfer_in";return `<tr><td><strong>${esc(c?.name||'Unknown')}</strong></td><td>${typeLabel(t.type)}</td><td class="${positive?'amount-positive':'amount-negative'}">${positive?'+':'-'}${vbFormatMoney(t.amount,c?.currency||t.currency||"USD")}</td><td><span class="badge ${statusClass(t.status)}">${esc(t.status)}</span></td><td>${vbRelativeDate(t.timestamp)}</td></tr>`}).join('')||`<tr><td colspan="5"><div class="empty-state">No transactions yet.</div></td></tr>`}
 function renderTop(){const cs=[...vbGetState().clients].sort((a,b)=>b.balance-a.balance).slice(0,5);$("#topClients").innerHTML=cs.map(c=>`<div class="client-row"><div class="avatar">${esc(vbInitials(c.name))}</div><div><strong>${esc(c.name)}</strong><small>${esc(c.accountNumber)} • ${esc(c.accountType)}</small></div><span class="balance-mini">${vbFormatMoney(c.balance,c.currency)}</span></div>`).join('')||`<div class="empty-state">No client accounts yet.</div>`}
 function renderClients(){const s=vbGetState(),q=$("#clientSearch").value.toLowerCase(),f=$("#clientStatusFilter").value,cs=s.clients.filter(c=>(!q||`${c.name} ${c.email} ${c.accountNumber}`.toLowerCase().includes(q))&&(f==='all'||c.status===f));$("#clientCount").textContent=`${cs.length} of ${s.clients.length} clients`;$("#clientsTable").innerHTML=cs.map(c=>{const n=s.transactions.filter(t=>t.clientId===c.id).length;return `<tr><td><div class="client-cell"><div class="avatar small">${esc(vbInitials(c.name))}</div><div><strong>${esc(c.name)}</strong><small>${esc(c.email)}</small></div></div></td><td><strong>${esc(c.accountNumber)}</strong><small>${esc(c.accountType)}</small></td><td><strong>${vbFormatMoney(c.balance,c.currency)}</strong></td><td>${n}</td><td><span class="badge ${statusClass(c.status)}">${esc(c.status)}</span></td><td><button class="action-btn" data-view-client="${esc(c.id)}">Manage</button> <button class="action-btn danger-action" data-delete-client="${esc(c.id)}">Delete</button></td></tr>`}).join('')||`<tr><td colspan="6"><div class="empty-state">No clients match your search.</div></td></tr>`}
 function renderTransactions(){const s=vbGetState(),q=$("#transactionSearch").value.toLowerCase(),f=$("#transactionFilter").value,st=$("#transactionStatusFilter").value,txs=s.transactions.filter(t=>{const c=clientFor(t,s);return (!q||`${t.id} ${c?.name||''} ${c?.accountNumber||''}`.toLowerCase().includes(q))&&(f==='all'||t.type===f)&&(st==='all'||t.status===st)});$("#transactionsTable").innerHTML=txs.map(t=>{const c=clientFor(t,s),positive=t.type==='deposit'||t.type==='transfer_in';return `<tr><td><strong>${esc(t.id)}</strong></td><td>${esc(c?.name||'Unknown')}</td><td>${esc(c?.accountNumber||'—')}</td><td>${typeLabel(t.type)}</td><td class="${positive?'amount-positive':'amount-negative'}">${positive?'+':'-'}${vbFormatMoney(t.amount,c?.currency||t.currency||"USD")}</td><td><span class="badge ${statusClass(t.status)}">${esc(t.status)}</span></td><td>${vbFormatDate(t.timestamp)}</td></tr>`}).join('')||`<tr><td colspan="7"><div class="empty-state">No transactions match your filters.</div></td></tr>`}
 function renderAudit(){const s=vbGetState(),q=$("#auditSearch").value.toLowerCase(),items=s.audit.filter(a=>!q||`${a.action} ${a.details} ${a.actor}`.toLowerCase().includes(q));$("#auditListFull").innerHTML=items.map(a=>`<div class="audit-item"><div class="audit-icon">✓</div><div><strong>${esc(a.action)}</strong><p>${esc(a.details)}</p><small>${esc(a.actor)} • ${vbFormatDate(a.timestamp)}</small></div></div>`).join('')||`<div class="empty-state">No audit events yet.</div>`}
 function renderCurrencySettings(){
  const s=vbGetState(), code=s.bank.currency||"USD";
  const select=$("#currencySelect"); if(select) select.value=code;
  const current=$("#currentCurrencyCode"); if(current) current.textContent=`${code} — ${vbGetCurrency(code).symbol}`;
  const limit=$("#dailyLimitDisplay"); if(limit) limit.textContent=vbFormatMoney(TRANSFER_DAILY_LIMIT,code);
  const rates=s.bank.rates||{};
  [["rateUSDGBP","USD","GBP"],["rateUSDEUR","USD","EUR"],["rateGBPUSD","GBP","USD"],["rateGBPEUR","GBP","EUR"],["rateEURUSD","EUR","USD"],["rateEURGBP","EUR","GBP"]].forEach(([id,a,b])=>{const el=$("#"+id);if(el)el.value=rates[a]?.[b]||""});
  vbRenderCurrencyUI();
 }
 function renderAll(){renderStats();renderChart();renderStatus();renderRecent();renderTop();renderClients();renderTransactions();renderAudit();renderCurrencySettings()}
 function populateEdit(c){const ph=splitPhone(c.phone);$("#editClientId").value=c.id;$("#editName").value=c.name;$("#editEmail").value=c.email;$("#editPhoneCode").value=ph.code;$("#editPhone").value=ph.local;$("#editDob").value=c.dob||'';$("#editAddress").value=c.address||'';$("#editAccountType").value=c.accountType;$("#editCurrency").value=c.currency||"USD";$("#editStatus").value=c.status;$("#editAccountNumber").textContent=c.accountNumber}
 function showDetails(id){const s=vbGetState(),c=s.clients.find(x=>x.id===id);if(!c)return;const txs=s.transactions.filter(t=>t.clientId===id);$("#clientDetails").innerHTML=`<div class="detail-head"><div class="detail-avatar">${esc(vbInitials(c.name))}</div><div><span class="eyebrow">CLIENT ACCOUNT</span><h2>${esc(c.name)}</h2><p>${esc(c.accountType)} • ${esc(vbGetCurrency(c.currency).code)} • <span class="badge ${statusClass(c.status)}">${esc(c.status)}</span></p></div></div><div class="detail-grid"><div class="detail-box"><span>Account number</span><strong>${esc(c.accountNumber)}</strong></div><div class="detail-box"><span>Current balance</span><strong>${vbFormatMoney(c.balance,c.currency)}</strong></div><div class="detail-box"><span>Email</span><strong>${esc(c.email)}</strong></div><div class="detail-box"><span>Phone</span><strong>${esc(c.phone||'Not provided')}</strong></div><div class="detail-box"><span>Date joined</span><strong>${vbShortDate(c.createdAt)}</strong></div><div class="detail-box"><span>Address</span><strong>${esc(c.address||'Not provided')}</strong></div></div><div class="detail-actions"><button class="primary-btn compact" data-edit-from-details="${esc(c.id)}">Edit profile</button><button class="secondary-btn compact" data-status-from-details="${esc(c.id)}">${c.status==='Active'?'Freeze account':'Activate account'}</button><button class="secondary-btn compact" data-password-from-details="${esc(c.id)}">Change password</button><button class="secondary-btn compact danger-action" data-delete-from-details="${esc(c.id)}">Delete client</button><button class="secondary-btn compact" data-statement-from-details="${esc(c.id)}">Statement</button></div><div class="panel inner-panel"><div class="panel-head"><div><span class="card-kicker">RECENT ACTIVITY</span><h3>Account history</h3></div></div><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Type</th><th>Amount</th><th>Date</th></tr></thead><tbody>${txs.slice(0,10).map(t=>`<tr><td>${esc(t.id)}</td><td>${typeLabel(t.type)}</td><td class="${t.type==='deposit'||t.type==='transfer_in'?'amount-positive':'amount-negative'}">${t.type==='deposit'||t.type==='transfer_in'?'+':'-'}${vbFormatMoney(t.amount,c?.currency||t.currency||"USD")}</td><td>${vbFormatDate(t.timestamp)}</td></tr>`).join('')||`<tr><td colspan="4"><div class="empty-state">No activity.</div></td></tr>`}</tbody></table></div></div>`;modal('clientDetailsModal')}
 $$('[data-section]').forEach(b=>b.onclick=()=>switchSection(b.dataset.section));
 $("#openPostTransaction").onclick=()=>{populatePostClients();modal("postTransactionModal",true)};
 $("#postClientId").onchange=updatePostBalance;
 $("#postTransactionType").onchange=updatePostBalance;$$('[data-go]').forEach(b=>b.onclick=()=>switchSection(b.dataset.go));$("#menuBtn").onclick=()=>{$("#sidebar").classList.toggle('open');$("#mobileOverlay").classList.toggle('open')};$("#mobileOverlay").onclick=()=>switchSection(document.querySelector('.nav-item.active')?.dataset.section||'overview');$$('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));$$('.modal-backdrop').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});$("#quickAddClient").onclick=()=>modal('clientModal');$("#addClientBtn").onclick=()=>modal('clientModal');
 function populatePostClients(){const s=vbGetState(),sel=$("#postClientId");if(!sel)return;sel.innerHTML=s.clients.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} — ${esc(c.accountNumber)} (${esc(vbGetCurrency(c.currency).code)})</option>`).join("")||`<option value="">No client accounts yet</option>`;updatePostBalance()}
 function updatePostBalance(){const c=vbFindClient($("#postClientId")?.value);const el=$("#postTransactionBalance");if(el)el.textContent=c?`Current balance: ${vbFormatMoney(c.balance,c.currency)} • Account currency: ${vbGetCurrency(c.currency).name}`:"Select a client to view their current balance.";const amt=$("#postTransactionAmount"),type=$("#postTransactionType"),rf=$("#postRecipientField");if(amt&&c){amt.placeholder=`Amount in ${vbGetCurrency(c.currency).code}`;if(type)type.dataset.currency=c.currency}if(rf&&type)rf.classList.toggle("hidden",type.value!=="transfer")}
 $("#createClientForm").onsubmit=e=>{e.preventDefault();try{const c=vbCreateClient({name:$("#newClientName").value,email:$("#newClientEmail").value,password:$("#newClientPassword").value,phone:normalizePhone($("#newClientPhoneCode").value,$("#newClientPhone").value),dob:$("#newClientDob").value,address:$("#newClientAddress").value,accountType:$("#newClientAccountType").value,currency:$("#newClientCurrency").value,initialBalance:$("#newClientBalance").value});e.target.reset();$("#newClientBalance").value='0';modal('clientModal',false);renderAll();toast(`Account ${c.accountNumber} created successfully.`);setTimeout(()=>showDetails(c.id),120)}catch(err){toast(err.message,'error')}};
 $("#postTransactionForm").onsubmit=e=>{e.preventDefault();try{const c=vbFindClient($("#postClientId").value);if(!c)throw new Error("Select a client account.");const type=$("#postTransactionType").value,status=$("#postTransactionStatus").value,a=Number($("#postTransactionAmount").value),desc=$("#postTransactionDescription").value||`Administrator ${type}`;if(type==="transfer"){const target=$("#postRecipientAccount").value.trim();if(!target)throw new Error("Enter the recipient account number.");const r=vbTransferFunds(c.id,target,a,desc);e.target.reset();modal("postTransactionModal",false);renderAll();showDetails(c.id);toast(`Transfer posted successfully • ${r.reference}`)}else{const t=vbAdminPostTransaction(c.id,type,a,status,desc);e.target.reset();modal("postTransactionModal",false);renderAll();showDetails(c.id);toast(`${type==="deposit"?"Deposit":"Withdrawal"} posted for ${c.name}.`)}}catch(err){toast(err.message,"error")}};
 $("#editClientForm").onsubmit=e=>{e.preventDefault();try{const id=$("#editClientId").value;vbUpdateClient(id,{name:$("#editName").value,email:$("#editEmail").value,phone:normalizePhone($("#editPhoneCode").value,$("#editPhone").value),dob:$("#editDob").value,address:$("#editAddress").value,accountType:$("#editAccountType").value,currency:$("#editCurrency").value,status:$("#editStatus").value});modal('editClientModal',false);renderAll();showDetails(id);toast('Client profile updated.')}catch(err){toast(err.message,'error')}};
 $("#clientsTable").onclick=e=>{const b=e.target.closest('[data-view-client]'),d=e.target.closest('[data-delete-client]');if(b){showDetails(b.dataset.viewClient);return;}if(d){const c=vbFindClient(d.dataset.deleteClient);if(c&&confirm(`Delete ${c.name}'s client account (${c.accountNumber})? This will permanently remove the client profile, balance and transaction history from this browser prototype.`)){try{vbDeleteClient(c.id);renderAll();toast(`Client ${c.name} deleted successfully.`)}catch(err){toast(err.message,'error')}}}};
 $("#clientDetails").onclick=e=>{const eb=e.target.closest('[data-edit-from-details]'),sb=e.target.closest('[data-status-from-details]'),pb=e.target.closest('[data-password-from-details]'),db=e.target.closest('[data-delete-from-details]'),stb=e.target.closest('[data-statement-from-details]');if(eb){const c=vbFindClient(eb.dataset.editFromDetails);populateEdit(c);modal('clientDetailsModal',false);modal('editClientModal')}if(sb){const c=vbFindClient(sb.dataset.statusFromDetails),next=c.status==='Active'?'Frozen':'Active';if(confirm(`Set ${c.name}'s account to ${next}?`)){vbSetClientStatus(c.id,next);renderAll();showDetails(c.id);toast(`Account ${next.toLowerCase()}.`)}}if(pb){const c=vbFindClient(pb.dataset.passwordFromDetails);$("#passwordClientId").value=c.id;$("#passwordClientName").textContent=c.name;$("#clientNewPassword").value='';modal('clientDetailsModal',false);modal('passwordModal')}if(db){const c=vbFindClient(db.dataset.deleteFromDetails);if(c&&confirm(`Delete ${c.name}'s client account (${c.accountNumber})? This will permanently remove the client profile, balance and transaction history from this browser prototype.`)){try{vbDeleteClient(c.id);modal('clientDetailsModal',false);renderAll();toast(`Client ${c.name} deleted successfully.`)}catch(err){toast(err.message,'error')}}}if(stb){vbExportStatement(stb.dataset.statementFromDetails,'','')}};
 $("#passwordForm").onsubmit=e=>{e.preventDefault();try{vbChangeClientPassword($("#passwordClientId").value,$("#clientNewPassword").value);modal('passwordModal',false);toast('Client password changed.')}catch(err){toast(err.message,'error')}};
 $("#saveCurrency").onclick=()=>{const code=$("#currencySelect").value;try{vbSetCurrency(code);renderAll();toast(`Default currency set to ${vbGetCurrency(code).name}. Existing client currencies were not changed.`)}catch(err){toast(err.message,"error")}};
 $("#saveRates").onclick=()=>{try{[["USD","GBP","rateUSDGBP"],["USD","EUR","rateUSDEUR"],["GBP","USD","rateGBPUSD"],["GBP","EUR","rateGBPEUR"],["EUR","USD","rateEURUSD"],["EUR","GBP","rateEURGBP"]].forEach(([a,b,id])=>vbSetExchangeRate(a,b,$("#"+id).value));toast("Exchange rates saved successfully.");renderCurrencySettings()}catch(err){toast(err.message,"error")}};
 $("#clientSearch").oninput=renderClients;$("#clientStatusFilter").onchange=renderClients;$("#transactionSearch").oninput=renderTransactions;$("#transactionFilter").onchange=renderTransactions;$("#transactionStatusFilter").onchange=renderTransactions;$("#auditSearch").oninput=renderAudit;
 $("#resetBankData").onclick=()=>{if(confirm('Reset all Velorian Bank client accounts, transactions and audit activity? This cannot be undone.')){vbResetBankData();renderAll();toast('Bank data reset. The system is empty again.')}};$("#adminLogout").onclick=()=>{vbClearSession();location.href='login.html'};window.addEventListener('velorian:statechange',renderAll);window.addEventListener('storage',renderAll);renderAll();
});
